const BOARD_1 = [
  [
    { name: '0', desc: '', dice: true, type: 1, active: false },
    { name: '1', desc: '', dice: true, type: 1, active: false },
    { name: '2', desc: '', dice: true, type: 1, active: false },
    { name: '3', desc: '', dice: true, type: 1, active: false },
    { name: '4', desc: '', dice: true, type: 1, active: false },
    { name: '5', desc: '', dice: true, type: 1, active: false },
    { name: '6', desc: '', dice: true, type: 1, active: false },
  ],
  [
    { name: '1', desc: '', dice: true, type: 1, active: false },
    { name: 'SHOT', desc: 'Eh eh eh! 😎', dice: false, type: 2, active: false },
    {
      name: 'Cachipun',
      desc: 'Piedra, papel o tijera(s),chin chan pu, pikachú, cachipún, jankenpón, yan ken po, pin pon papas, hakembó o how-are-you-speak',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'No parpadear',
      desc: 'Compite contra el ebrio de tu derecha quien puede aguantar mas sin parpadear',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Cantidad de vocales',
      desc: 'Toma por cada vocal que exista en tu nombre: Ana Maria (5 vocales)',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Juego del 7',
      desc: 'Cuenta del 1 al infinito sin decir digitos que tengan el 7 o multiplos del mismo. Ejem. 1,2,3,4,5,6,8.....13,15,16',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Cuenta una historia',
      desc: 'El ebrio principal, en este caso tú debes comenzar con una frase, ejemplo "el auto" y el siguiente continuara añadiendo una palabra. Quien no recuerde todas las palabras tomará ',
      dice: false,
      type: 4,
      active: false,
    },
  ],
  [
    { name: '2', desc: '', dice: true, type: 1, active: false },
    {
      name: 'Inglish Chicken',
      desc: 'Atrapa el pulgar del ebrio de tu derecha, quien pierda debe tomar.',
      dice: false,
      type: 4,
      active: false,
    },
    { name: 'SHOT', desc: 'JAJAJA! 😈', dice: false, type: 2, active: false },
    {
      name: 'El piso es Lava',
      desc: 'Grita el PISO ES LAVA!. El último en salir del piso debe tomar',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Matar - Casar - Culiar',
      desc: 'Escoge famoso, alien, pelicula, planta. Tu decides. Si no quieres, a tomar!',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Nunca nunca',
      desc: 'Comienza con la frase "Yo nunca nunca...", no importa si lo haz hecho o no.',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Descansa, pasa al siguiente',
      desc: 'Tomate un break en esta ronda, hazlo por tu higado!',
      dice: false,
      type: 4,
      active: false,
    },
  ],
  [
    { name: '3', desc: '', dice: true, type: 1, active: false },
    {
      name: 'Cultura Chupistica',
      desc: 'La cultura chupistica dice ...',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Ropa color',
      desc: 'Toma por cada prenda que tengas del color ...',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'SHOT',
      desc: 'Lo mereces no mientas! 😝',
      dice: false,
      type: 2,
      active: false,
    },
    {
      name: 'El mas joven',
      desc: 'El o los jugadores mas jovenes regalan 4 tragos',
      dice: false,
      type: 4,
      active: false,
    },
    { name: 'El mas', desc: 'algo toma', dice: false, type: 4, active: false },
    {
      name: 'Toma un descanso',
      desc: 'Debe ser el destino, puedes descansar esta ronda',
      dice: false,
      type: 4,
      active: false,
    },
  ],
  [
    { name: '4', desc: '', dice: true, type: 1, active: false },
    {
      name: '3 verdades y 1 mentira',
      desc: 'Cuenta 3 verdades y 1 mentira. Pregunta al resto en orden cual de ellas es verdad o mentira. Quien no logre adivinar debera tomar.',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Africano',
      desc: 'Bueno ... tu sabes.',
      dice: false,
      type: 4,
      active: false,
    },
    { name: 'El mas', desc: 'algo toma', dice: false, type: 4, active: false },
    {
      name: 'SHOT',
      desc: 'Sin excusas! 👀',
      dice: false,
      type: 2,
      active: false,
    },
    {
      name: 'Celular',
      desc: 'Los jugadores con celulares de esta marca debera beber:',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Ultimo mensaje',
      desc: 'Deberas leer el ultimo mensaje recibido. El resto de jugadores debera escoger entre Whatsapp, facebook, instagram o texto. Recuerda! siempre puedes pasar y beber.',
      dice: false,
      type: 4,
      active: false,
    },
  ],
  [
    { name: '5', desc: '', dice: true, type: 1, active: false },
    {
      name: 'Nunca nunca',
      desc: 'Yo nunca nunca ...',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Regla',
      desc: 'Inventa una regla para el resto, cada vez que esta se rompa deberan beber todos!',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Chancho Inflao',
      desc: 'Creo que no necesito explicarlo.',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Farol',
      desc: 'Ese farol no alumbra...',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'SHOT',
      desc: 'Hasta el fondo! 😳',
      dice: false,
      type: 2,
      active: false,
    },
    { name: 'El mas', desc: 'algo toma', dice: false, type: 4, active: false },
  ],
  [
    { name: '6', desc: '', dice: true, type: 1, active: false },
    {
      name: 'El submarino',
      desc: '....',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Agua',
      desc: 'Rehidrata tu cuerpo!',
      dice: false,
      type: 4,
      active: false,
    },
    { name: 'El mas', desc: 'algo toma', dice: false, type: 4, active: false },
    {
      name: 'Cultura chupistica',
      desc: 'La cultura chupistica pide:',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'Andale',
      desc: 'Aun nose como se juega...',
      dice: false,
      type: 4,
      active: false,
    },
    {
      name: 'SHOT',
      desc: 'Es tu dia de suerte! 🥴',
      dice: false,
      type: 2,
      active: false,
    },
  ],
]

export { BOARD_1 }
