const BOARD_1 = [
  [
    { name: '0', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '1', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '2', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '3', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '4', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '5', desc: '', dice: true, type: 1, active: false, random: [] },
    { name: '6', desc: '', dice: true, type: 1, active: false, random: [] },
  ],
  [
    { name: '1', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: 'SHOT',
      desc: 'Eh eh eh! 😎',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
    {
      name: 'Cachipun',
      desc: 'Juega con el jugador de tu derecha, quien pierda deberá tomar 👊 🖐 🖖',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'No parpadear 👀',
      desc: 'Compite contra el jugador de tu derecha quien puede aguantar mas sin parpadear ganará o perderá... depende como lo veas 🧐',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Vocales',
      desc: 'Todos juegan ! Cada jugador deberá tomar por cada vocal existente en su nombre. Ej: Ana (2 vocales)',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Juego del 7',
      desc: 'Todos juegan! Cuenta del 1 al infinito sin decir digitos que tengan el 7 o multiplos del mismo. Recuerda debes aplaudir por cada número que aparezca Ejem. 1,2,3,4,5,6,Aplaudir, 8...20, Aplaudir, 22,23...',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Cuenta una historia',
      desc: 'El jugador inicial, en este caso tú debes comenzar con una frase, ejemplo "el auto" y el siguiente (a tu derecha) continuará añadiendo una palabra. Quien no recuerde todas las palabras tomará ',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
  ],
  [
    { name: '2', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: 'Gallito Ingles',
      desc: 'Todos juegan! Atrapa el pulgar del jugador de tu derecha, quien pierda deberá tomar.',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'SHOT',
      desc: 'JAJAJA! 😈',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
    {
      name: 'El piso es Lava 🌋',
      desc: 'Grita el PISO ES LAVA!. El último que deje de tocar el piso deberá tomar',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Matar - Casar - Culiar',
      desc: 'Escoge famoso, alien, pelicula, planta. Tu decides. Si no quieres, a tomar!',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Nunca nunca',
      desc: '🌚 🌝',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Yo nunca nunca he trabajado borracho.',
        'Yo nunca nunca he consumido drogas.',
        'Yo nunca nunca he hecho un trío.',
        'Yo nunca nunca he hecho o recibido un baile erótico.',
        'Yo nunca nunca he robado nada en una tienda.',
        'Yo nunca nunca he mentido a mis amigos',
        'Yo nunca nunca he dicho el nombre equivocado durante las relaciones sexuales.',
        'Yo nunca nunca me he liado con el ex de un/a amigo/a.',
        'Yo nunca nunca he estado con alguien este grupo.',
        'Yo nunca nunca nadé desnudo.',
      ],
    },
    {
      name: 'Descansa, pasa al siguiente',
      desc: 'Tomate un break en esta ronda, hazlo por tu higado!',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
  ],
  [
    { name: '3', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: 'Cultura 🏛',
      desc: 'La cultura chupistica pide',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Partes del cuerpo que hay solo 1, como por Ejemplo: La nariz.',
        'Partes del cuerpo que crecen, como por Ejemplo:las uñas.',
        'Nombres o sobrenombres del miembro feminino, como por Ejemplo: cuca',
        'Nombres que terminen con "o", como por Ejemplo: Pablo',
        'Garabatos chilenos, como por Ejemplo: CTM 🤬',
        'Razas de perros, como por Ejemplo: Pastor Aleman',
        'Palabras que no tengan la letra "a" como por Ejemplo: Libro, Pulmon, etc.',
        'Planetas del sistema solar, como por Ejemplo: Tierra',
        'Marcas de cervezas, como por Ejemplo: Budweiser',
        'Nombres o sobrenombres del miembro masculino, como por Ejemplo: niño',
        'Cuenta regresiva desde el 13 hasta el 1',
        'Nombres de mujeres sin la letra A, como por Ejemplo: Genesis',
        'Nombre de paises dentro de Europa, como por Ejemplo: Alemania',
      ],
    },
    {
      name: 'Ropa color',
      desc: 'Toma por cada prenda (🧦 👕 👠) que tengas del color:',
      dice: false,
      type: 4,
      active: false,
      random: ['Rojo', 'Negro', 'Blanco', 'Grises', 'Verde'],
    },
    {
      name: 'SHOT',
      desc: 'Lo mereces no mientas! 😝',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
    {
      name: 'El mas joven',
      desc: 'El o los jugadores mas jovenes regalan 4 tragos',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'MAS',
      desc: '🍷',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Le + joven toma',
        'Le + poton/a toma',
        'Le + viejo/a toma',
        'Le + ciego/a',
        'Le + rusio/a',
        'Le + pesado/a',
        'Le + bromista',
        'Le + nerd',
      ],
    },
    {
      name: 'Andale 🌮',
      desc: 'Aun nose como se juega...',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
  ],
  [
    { name: '4', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: '3 verdades y 1 mentira',
      desc: 'Cuenta 3 verdades y 1 mentira. Pregunta al resto en orden cual de ellas es verdad o mentira. Quien no logre adivinar debera tomar.',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Africano',
      desc: 'Bueno ... tu sabes.',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'MAS',
      desc: '🍷',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Le + joven toma',
        'Le + poton/a toma',
        'Le + viejo/a toma',
        'Le + ciego/a toma',
        'Le + rusio/a toma',
        'Le + pesado/a toma',
        'Le + bromista toma',
        'Le + nerd toma',
      ],
    },
    {
      name: 'SHOT',
      desc: 'Sin excusas! 👀',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
    {
      name: 'Celular 📞',
      desc: 'Los jugadores con celulares de esta marca deberan beber:',
      dice: false,
      type: 4,
      active: false,
      random: ['Celulares Android', 'Celulares Apple'],
    },
    {
      name: 'Ultimo mensaje',
      desc: 'Deberas leer el ultimo mensaje recibido. El resto de jugadores debera escoger entre Whatsapp, facebook, instagram o texto. Recuerda! siempre puedes pasar y beber.',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
  ],
  [
    { name: '5', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: 'Nunca nunca',
      desc: '🌝 🌚',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Yo nunca nunca pensé que soy la persona más bella de este grupo.',
        'Yo nunca nunca he tenido una época vegetariana o vegana.',
        'Yo nunca nunca he vuelto con mi expareja.',
        'Yo nunca nunca envié una mensaje fuerte o descarado a la persona equivocada.',
        'Yo nunca nunca he estado esposado (por cualquier motivo).',
        'Yo nunca nunca he estado con un extraño.',
        'Yo nunca nunca he olido mi propia ropa interior para ver si está limpia o sucia.',
        'Yo nunca nunca he sido infiel.',
        'Yo nunca nunca he conocido a alguien famoso',
        'Yo nunca nunca he tenido miedo de los payasos',
      ],
    },
    {
      name: 'Regla ⚡',
      desc: 'Inventa una regla para el resto, cada vez que esta se rompa deberan beber todos!',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Chancho Inflao',
      desc: 'Puedes inflar el chancho en cualquier ronda, pero recuerda el ultimo en inflarse debera tomar.',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Farol 💣',
      desc: 'Ese farol no alumbra...',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'SHOT',
      desc: 'Hasta el fondo! 😳',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
    {
      name: 'Limón-Melón 🍋🍈',
      desc: 'Comienza con "Un limón, medio limón dos limones", el de tu derecha deberá seguir con "Dos limones, medio limón tres limones", y asi sucesivamente...',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
  ],
  [
    { name: '6', desc: '', dice: true, type: 1, active: false, random: [] },
    {
      name: 'El submarino',
      desc: '🧊🥃',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'Cultura 🏛',
      desc: 'La cultura chupistica pide:',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Partes del cuerpo que hay solo 1, como por Ejemplo: La nariz.',
        'Partes del cuerpo que crecen, como por Ejemplo:las uñas.',
        'Nombres o sobrenombres del miembro feminino, como por Ejemplo: cuca',
        'Nombres que terminen con "o", como por Ejemplo: Pablo',
        'Garabatos chilenos, como por Ejemplo: CTM 🤬',
        'Razas de perros, como por Ejemplo: Pastor Aleman',
        'Palabras que no tengan la letra "a" como por Ejemplo: Libro, Pulmon, etc.',
        'Planetas del sistema solar, como por Ejemplo: Tierra',
        'Marcas de cervezas, como por Ejemplo: Budweiser',
        'Nombres o sobrenombres del miembro masculino, como por Ejemplo: niño',
        'Cuenta regresiva desde el 13 hasta el 1',
        'Nombres de mujeres sin la letra A, como por Ejemplo: Genesis',
        'Nombre de paises dentro de Europa, como por Ejemplo: Alemania',
      ],
    },
    {
      name: 'MAS',
      desc: '🍷',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Le + joven toma',
        'Le + poton/a toma',
        'Le + viejo/a toma',
        'Le + ciego/a toma',
        'Le + rusio/a toma',
        'Le + pesado/a toma',
        'Le + bromista toma',
        'Le + nerd toma',
      ],
    },
    {
      name: 'Cultura 🏛',
      desc: 'La cultura chupistica pide:',
      dice: false,
      type: 4,
      active: false,
      random: [
        'Partes del cuerpo que hay solo 1, como por Ejemplo: La nariz.',
        'Partes del cuerpo que crecen, como por Ejemplo:las uñas.',
        'Nombres o sobrenombres del miembro feminino, como por Ejemplo: cuca',
        'Nombres que terminen con "o", como por Ejemplo: Pablo',
        'Garabatos chilenos, como por Ejemplo: CTM 🤬',
        'Razas de perros, como por Ejemplo: Pastor Aleman',
        'Palabras que no tengan la letra "a" como por Ejemplo: Libro, Pulmon, etc.',
        'Planetas del sistema solar, como por Ejemplo: Tierra',
        'Marcas de cervezas, como por Ejemplo: Budweiser',
        'Nombres o sobrenombres del miembro masculino, como por Ejemplo: niño',
        'Cuenta regresiva desde el 13 hasta el 1',
        'Nombres de mujeres sin la letra A, como por Ejemplo: Genesis',
        'Nombre de paises dentro de Europa, como por Ejemplo: Alemania',
      ],
    },
    {
      name: 'Andale 🌮',
      desc: 'Aun nose como se juega...',
      dice: false,
      type: 4,
      active: false,
      random: [],
    },
    {
      name: 'SHOT',
      desc: 'Es tu dia de suerte! 🥴',
      dice: false,
      type: 2,
      active: false,
      random: [],
    },
  ],
]

export { BOARD_1 }
